#!/bin/bash
echo "Filtering Google Sign-In logs..."
echo "Look for lines containing:"
echo "  - '=== Initializing Google Sign-In ==='"
echo "  - '=== Starting Google Sign-In ==='"
echo "  - '=== Authentication Event ==='"
echo "  - '=== Google Sign-In Exception ==='"
echo "  - 'GetCredentialResponse'"
echo "  - 'CredManProvService'"
echo ""
echo "To filter logs in real-time, run:"
echo "  flutter run 2>&1 | grep -E '(Google|CredMan|Sign-In|Authentication|===)'"
echo ""
echo "Or use adb logcat:"
echo "  adb logcat | grep -E '(flutter|GoogleSignIn|CredMan|GetCredential)'"
